language: perl
perl:
  - 5.22
  - 5.20
  - 5.18
  - 5.16
  - 5.14
  - 5.12
  - 5.10
  - 5.8
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
install:
  - cpanm -n CPAN
  - (echo y; echo y; echo o conf commit) | cpan
  - (cpanm --with-develop --installdeps --notest .) || cat ~/.cpanm/build.log
before_script:
  - perl Makefile.PL
  - make
script:
  - prove -bv t
  - prove -bv xt
notifications:
  on_success: change
  on_failure: change

